Repository hugolinhareso/ticket-machine, pull requests merged in 2023-09, with the labels that each got.

#14 fix: fixed while loops in Troco constructor
  src/br/calebe/ticketmachine/core/Troco.java
Labels: desempenho

#16 fix: removed 'remove' method
  src/br/calebe/ticketmachine/core/Troco.java
Labels: excesso

#15 fix: hasNext() and next() methods revised
  src/br/calebe/ticketmachine/core/Troco.java
Labels: controle

#19 fix: valor parameter changed to precoDoBilhete
  src/br/calebe/ticketmachine/core/TicketMachine.java
Labels: comissão

#21 Fix ticketmachine get troco
  src/br/calebe/ticketmachine/core/TicketMachine.java
Labels: comissão

#20 fix: PapelMoedaInvalidaException
  src/br/calebe/ticketmachine/exception/PapelMoedaInvalidaException.java
Labels: melhoria

#22 fix: fixed i index utilization
  src/br/calebe/ticketmachine/core/TicketMachine.java
Labels: dados

#23 fix: Error Handling on SaldoInsuficienteException
  src/br/calebe/ticketmachine/exception/SaldoInsuficienteException.java
Labels: melhoria
